version: '3.7'
services: 
    bitcoinetl:
        restart: always
        image: bitcoinetl:01
        build: ./bitcoin-etl
        command: stream --provider-uri=${provider_uri} --lag=${lag} --batch-size=${batch_size} --block-batch-size=${block_batch_size} --max-workers=${max_workers} --last-synced-block-file=${last_synced_block_file}  --output="${db_service_name}://${db_user}:${db_pass}@${db_host}:${db_port}/${db_name}?authSource=${auth_db_name}"
        volumes:
        - ./bitcoin-etl:/bitcoin-etl
        - ~/.aws:/root/.aws
        - logvolumeetl01:/var/log
        network_mode: "host"
volumes:
    logvolumeetl01: